name: state_persistence
description: Persist state across app launches. By default this library store
  state as a local JSON file called `data.json` in the applications
  data directory.
version: 0.0.5
authors:
  - Flutter Community <community@flutter.zone>
  - Simon Lightfoot <simon@devangels.london>
homepage: https://github.com/fluttercommunity/state_persistence
maintainer: Simon Lightfoot (@slightfoot)

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path: ^1.6.4
  path_provider: ^1.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
